apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: configuration-server
  name: configuration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: configuration-server
    spec:
      containers:
      - image: alexsrocha/configuration-server
        name: configuration-server
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: configuration-server
  name: configuration-server
spec:
  ports:
  - name: 8888-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: configuration-server
  type: ClusterIP
status:
  loadBalancer: {}
